tasks:
  - init: make bundle-install
    command: make bundle-install && make install-conda && make create-env && source /home/gitpod/miniconda3/bin/activate && conda activate galaxy_training_material

ports:
  - port: 4000
    onOpen: open-preview
    visibility: public
